apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: cast
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fastapiapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cast
  template:
    metadata:
      labels:
        {{- include "fastapiapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cast
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fastapiapp.serviceAccountName" . }}
      containers:
        - name: cast-service
          image: "{{ .Values.cast_service.image.repository }}:{{ .Values.cast_service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cast_service.image.pullPolicy }}
          env:
          - name: DATABASE_URI
            value: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/casts/docs
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/casts/docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
