apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  labels:
    app.kubernetes.io/component: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: movie-db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: movie-db
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        env:
        - name: POSTGRES_USER
          value: "movie_db_username"
        - name: POSTGRES_PASSWORD
          value: "movie_db_password"
        - name: POSTGRES_DB
          value: "movie_db_dev"
        ports:
        - containerPort: 5432
