apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
  labels:
    app.kubernetes.io/component: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: cast-db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cast-db
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        env:
        - name: POSTGRES_USER
          value: "cast_db_username"
        - name: POSTGRES_PASSWORD
          value: "cast_db_password"
        - name: POSTGRES_DB
          value: "cast_db_dev"
        ports:
        - containerPort: 5432
