apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: cast
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.cast_service.service.port }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }} # Attention, ne pas utiliser le même NodePort pour les deux services si activé
      {{- end }}
  selector:
    {{- include "fastapiapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cast
