apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-movie
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: movie
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.movie_service.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fastapiapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: movie
